# Reusable composite action for Python environment setup
# Standardizes Python and dependency installation across all workflows
# Version: 1.0.0

name: "Setup Python Environment"
description: "Setup Python with uv and install project dependencies with caching"

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.12"
  install-deps:
    description: "Install dependencies with uv sync"
    required: false
    default: "true"
  extras:
    description: "Extra dependencies to install (MUST be --all-extras for dev/test)"
    required: false
    default: "--all-extras"
  dev-group:
    description: "Install dev dependency group (MANDATORY for all test environments)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ inputs.python-version }}
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      run: |
        # CRITICAL: ALL test/dev environments MUST install ALL dependencies
        # Configuration drift between local and CI causes test failures
        SYNC_CMD="uv sync ${{ inputs.extras }}"
        if [ "${{ inputs.dev-group }}" == "true" ]; then
          SYNC_CMD="$SYNC_CMD --group dev"
        fi

        # ENFORCE: extras must be --all-extras for test environments
        if [[ "${{ inputs.extras }}" != *"--all-extras"* ]] && [[ "${{ inputs.extras }}" != "--no-dev" ]]; then
          echo "::warning::POLICY VIOLATION: Test environments must use --all-extras"
          echo "::warning::Current extras: ${{ inputs.extras }}"
          echo "::warning::Forcing --all-extras to prevent configuration drift"
          SYNC_CMD="uv sync --all-extras --group dev"
        fi

        echo "Running: $SYNC_CMD"
        $SYNC_CMD

        # Verify critical dependencies are installed
        echo "::group::Dependency Verification"
        uv pip list | grep -E "(pytest|matplotlib|numpy|scipy|cantools|hypothesis)" || \
          (echo "::error::CRITICAL: Core test dependencies missing!" && exit 1)
        echo "::endgroup::"
      shell: bash

    - name: Verify installation
      run: |
        echo "::group::Python Environment Info"
        uv run python --version
        uv run python -c "import sys; print(f'Python: {sys.executable}')"
        echo "::endgroup::"
      shell: bash
