# Reusable composite action for Python environment setup
# Standardizes Python and dependency installation across all workflows
# Version: 1.0.0

name: "Setup Python Environment"
description: "Setup Python with uv and install project dependencies with caching"

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.12"
  install-deps:
    description: "Install dependencies with uv sync"
    required: false
    default: "true"
  extras:
    description: "Extra dependencies to install (--all-extras, --dev, etc.)"
    required: false
    default: "--all-extras"
  dev-group:
    description: "Install dev dependency group (adds --group dev)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        # Pin UV version to avoid transient GitHub API failures
        # Update periodically instead of fetching "latest" on every run
        uv-version: "0.9.27"
        # Use GitHub token for higher API rate limits and better reliability
        github-token: ${{ github.token }}

    - name: Set up Python ${{ inputs.python-version }}
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      run: |
        # Build sync command with extras and dev group
        SYNC_CMD="uv sync ${{ inputs.extras }}"
        if [ "${{ inputs.dev-group }}" == "true" ]; then
          SYNC_CMD="$SYNC_CMD --group dev"
        fi
        echo "Running: $SYNC_CMD"
        $SYNC_CMD
      shell: bash

    - name: Verify installation
      run: |
        echo "::group::Python Environment Info"
        uv run python --version
        uv run python -c "import sys; print(f'Python: {sys.executable}')"
        echo "::endgroup::"
      shell: bash
