"""Hardware Integration: Real-time data acquisition patterns.

Demonstrates:
- Hardware abstraction layer patterns
- Real-time data acquisition simulation
- Hardware configuration management
- Error handling for hardware failures
- Mock hardware sources for testing

Category: Integration
IEEE Standards: N/A

Related Demos:
- 01_data_loading/01_waveforms.py
- 02_basic_analysis/01_measurements.py

This demonstrates patterns for integrating Oscura with hardware sources
like oscilloscopes, logic analyzers, and network interfaces. Uses mock
hardware for demonstration since actual hardware may not be available.

Note: This demo uses mock/simulated hardware since actual hardware
(SocketCAN, Saleae, oscilloscopes) may not be present. The patterns
shown are production-ready and can be adapted to real hardware.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

# Add demos to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import numpy as np

from demos.common import BaseDemo, ValidationSuite, print_header, print_info, print_subheader


class HardwareIntegrationDemo(BaseDemo):
    """Demonstrates hardware integration patterns."""

    name = "Hardware Integration"
    description = "Real-time hardware data acquisition patterns"
    category = "integration"

    def generate_data(self) -> None:
        """Initialize mock hardware."""
        # Data will be generated by mock hardware during acquisition
        pass

    def run_analysis(self) -> None:
        """Demonstrate hardware integration patterns."""
        from oscura.core import TraceMetadata, WaveformTrace

        print_header("Hardware Integration Patterns")

        print_subheader("1. Hardware Abstraction Layer")
        print_info("Define abstract interface for hardware sources")

        # Base hardware source interface
        class HardwareSource:
            """Abstract base class for hardware data sources."""

            def connect(self) -> bool:
                """Connect to hardware device."""
                raise NotImplementedError

            def disconnect(self) -> None:
                """Disconnect from hardware device."""
                raise NotImplementedError

            def configure(self, config: dict) -> None:
                """Configure hardware parameters."""
                raise NotImplementedError

            def acquire(self, duration: float) -> WaveformTrace:
                """Acquire data from hardware."""
                raise NotImplementedError

            def get_status(self) -> dict:
                """Get hardware status."""
                raise NotImplementedError

        print_info("✓ HardwareSource abstract interface defined")

        print_subheader("2. Mock Oscilloscope Implementation")

        class MockOscilloscope(HardwareSource):
            """Mock oscilloscope for testing."""

            def __init__(self, device_id: str = "MOCK-OSC-001"):
                self.device_id = device_id
                self.connected = False
                self.sample_rate = 1e6  # 1 MSa/s
                self.vertical_scale = 1.0  # V/div

            def connect(self) -> bool:
                time.sleep(0.05)  # Simulate connection delay
                self.connected = True
                return True

            def disconnect(self) -> None:
                self.connected = False

            def configure(self, config: dict) -> None:
                if not self.connected:
                    raise RuntimeError("Oscilloscope not connected")
                self.sample_rate = config.get("sample_rate", self.sample_rate)
                self.vertical_scale = config.get("vertical_scale", self.vertical_scale)

            def acquire(self, duration: float) -> WaveformTrace:
                if not self.connected:
                    raise RuntimeError("Oscilloscope not connected")

                # Generate simulated data
                num_samples = int(duration * self.sample_rate)
                t = np.linspace(0, duration, num_samples)
                data = np.sin(2 * np.pi * 1000 * t) * self.vertical_scale
                data += np.random.normal(0, 0.01, num_samples)  # Noise

                return WaveformTrace(
                    data=data,
                    metadata=TraceMetadata(
                        sample_rate=self.sample_rate,
                        channel_name="CH1",
                    ),
                )

            def get_status(self) -> dict:
                return {
                    "device_id": self.device_id,
                    "connected": self.connected,
                    "sample_rate": self.sample_rate,
                    "vertical_scale": self.vertical_scale,
                }

        # Demonstrate oscilloscope usage
        print_info("Creating mock oscilloscope...")
        osc = MockOscilloscope()

        print_info("Connecting...")
        connected = osc.connect()
        print_info(f"✓ Connected: {connected}")

        print_info("Configuring...")
        osc.configure({"sample_rate": 100e3, "vertical_scale": 1.0})
        print_info("✓ Configuration applied")

        status = osc.get_status()
        for key, value in status.items():
            print_info(f"  {key}: {value}")

        print_info("Acquiring data...")
        trace = osc.acquire(duration=0.01)
        print_info(f"✓ Acquired {len(trace.data)} samples")

        osc.disconnect()
        print_info("✓ Disconnected")

        self.results["oscilloscope_samples"] = len(trace.data)
        self.results["oscilloscope_connected"] = connected

        print_subheader("3. Error Handling for Hardware")

        def safe_acquire(hardware: HardwareSource, duration: float) -> WaveformTrace | None:
            """Safely acquire data with error handling and retry."""
            max_retries = 3
            retry_delay = 0.5

            for attempt in range(max_retries):
                try:
                    status = hardware.get_status()
                    if not status.get("connected", False):
                        hardware.connect()

                    trace = hardware.acquire(duration)
                    return trace

                except RuntimeError as e:
                    print_info(f"  Attempt {attempt + 1} failed: {e}")
                    if attempt < max_retries - 1:
                        time.sleep(retry_delay)
                    else:
                        print_info(f"  ✗ Failed after {max_retries} attempts")
                        return None

            return None

        test_hw = MockOscilloscope()
        result = safe_acquire(test_hw, duration=0.01)
        if result:
            print_info(f"✓ Successfully acquired {len(result.data)} samples with retry logic")
            self.results["safe_acquire_samples"] = len(result.data)

        print_subheader("4. Hardware Factory Pattern")

        class HardwareFactory:
            """Factory for creating hardware sources."""

            @staticmethod
            def create(hw_type: str, config: dict) -> HardwareSource:
                if hw_type == "oscilloscope":
                    return MockOscilloscope(device_id=config.get("device_id", "OSC-001"))
                else:
                    raise ValueError(f"Unknown hardware type: {hw_type}")

        hw = HardwareFactory.create("oscilloscope", {"device_id": "TEST-OSC-001"})
        print_info(f"✓ Created: {type(hw).__name__}")

        print_subheader("5. Configuration Management")

        hardware_config = {
            "oscilloscope": {
                "device_id": "OSC-001",
                "interface": "USB",
                "sample_rate": 100e3,
                "channels": [
                    {"id": "CH1", "enabled": True, "vertical_scale": 1.0},
                    {"id": "CH2", "enabled": False, "vertical_scale": 2.0},
                ],
            }
        }

        import json

        config_path = self.data_dir / "hardware_config.json"
        config_path.write_text(json.dumps(hardware_config, indent=2))
        print_info(f"✓ Configuration saved: {config_path}")

        self.results["config_path"] = str(config_path)

    def validate_results(self, suite: ValidationSuite) -> None:
        """Validate hardware integration results."""
        suite.check_exists("Oscilloscope samples", self.results.get("oscilloscope_samples"))
        suite.check_exists("Oscilloscope connected", self.results.get("oscilloscope_connected"))
        suite.check_exists("Safe acquire samples", self.results.get("safe_acquire_samples"))
        suite.check_exists("Config path", self.results.get("config_path"))


if __name__ == "__main__":
    demo = HardwareIntegrationDemo()
    result = demo.run()
    sys.exit(0 if result.success else 1)
